//! Filltype-compatibility bridge generator — the "sugar beet" fix.
//!
//! FS vehicles/stations accept fill types BY CATEGORY (a trailer takes `BULK`, a
//! shovel `SHOVEL`, …). When a map adds a custom fill type that isn't a member of the
//! categories your equipment handles, nothing can harvest / haul / store / sell it —
//! and there's no way to fix it in-game without editing the mods.
//!
//! Silo generates a tiny standalone COMPANION mod that adds the fill type(s) into the
//! categories you choose. Verified against the game (FillTypeManager.lua) and two live
//! mods (FS25_AdditionalFilltypes, FS25_ForageMixing): a mod's `<fillTypeCategory>`
//! lists fill-type NAMES to add to an existing category — an additive membership insert
//! that needs NO edit to the vehicle mods and NO redefinition of the fill type (it's
//! referenced by name). MP-safe like any data mod (all players just need the companion).
//!
//! XML shapes here mirror the real working mods exactly; the generator does not invent
//! structure. descVersion 105 is confirmed-loading on this FS25 build.

use std::io::{Cursor, Write};
use std::path::Path;

/// A bridge to generate. Names are normalized to the game's UPPER-cased registry keys.
#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSpec {
    /// FS25_-prefixed tech name / zip base name.
    pub tech_name: String,
    pub title: String,
    /// Fill-type names to bridge (e.g. ["SUGARBEET", "BEETPULP"]).
    pub fill_types: Vec<String>,
    /// Target categories to add them to (e.g. ["BULK", "SHOVEL", "TRAINWAGON"]).
    pub categories: Vec<String>,
}

const DESC_VERSION: u32 = 105;

/// Keep only the characters FS uses in registry names; upper-case. Empty if nothing left.
fn norm_name(s: &str) -> String {
    s.trim()
        .to_uppercase()
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect()
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// The companion's `fillTypes.xml` — category memberships only, referencing existing
/// fill types by name (no `<fillType>` definitions, so no textures/assets needed).
pub fn build_fill_types_xml(fill_types: &[String], categories: &[String]) -> String {
    let names: Vec<String> = fill_types.iter().map(|s| norm_name(s)).filter(|s| !s.is_empty()).collect();
    let joined = names.join(" ");
    let mut cats = String::new();
    for c in categories {
        let c = norm_name(c);
        if c.is_empty() {
            continue;
        }
        cats.push_str(&format!("        <fillTypeCategory name=\"{c}\">{joined}</fillTypeCategory>\n"));
    }
    format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\" ?>\n\
<map xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n\
    <fillTypes>\n\
        <fillTypeCategories>\n\
{cats}\
        </fillTypeCategories>\n\
    </fillTypes>\n\
</map>\n"
    )
}

/// A schema-valid FS25 `modDesc.xml` for the companion (iconFilename is required).
pub fn build_moddesc(title: &str, fill_types: &[String], categories: &[String]) -> String {
    let title = xml_escape(title.trim());
    let ftl = fill_types.iter().map(|s| norm_name(s)).filter(|s| !s.is_empty()).collect::<Vec<_>>().join(", ");
    let ctl = categories.iter().map(|s| norm_name(s)).filter(|s| !s.is_empty()).collect::<Vec<_>>().join(", ");
    let desc = xml_escape(&format!(
        "Compatibility bridge generated by Silo. Adds fill type(s) [{ftl}] to categorie(s) [{ctl}] so any equipment that accepts those categories can handle them. Adds nothing else — data only, multiplayer-safe."
    ));
    format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>\n\
<modDesc descVersion=\"{DESC_VERSION}\">\n\
    <author>Silo</author>\n\
    <version>1.0.0.0</version>\n\
    <title><en>{title}</en></title>\n\
    <description><en>{desc}</en></description>\n\
    <iconFilename>icon.png</iconFilename>\n\
    <multiplayer supported=\"true\"/>\n\
    <fillTypes filename=\"fillTypes.xml\"/>\n\
</modDesc>\n"
    )
}

/// A plain 256×256 PNG mod icon (Silo green with a lighter inset) — no font/assets needed.
fn make_icon() -> Result<Vec<u8>, String> {
    let mut img = image::RgbaImage::from_pixel(256, 256, image::Rgba([74, 115, 48, 255])); // --green-600
    for y in 0..256u32 {
        for x in 0..256u32 {
            if (32..224).contains(&x) && (32..224).contains(&y) {
                img.put_pixel(x, y, image::Rgba([156, 192, 110, 255])); // --green-300 inset
            }
        }
    }
    let mut buf = Vec::new();
    img.write_to(&mut Cursor::new(&mut buf), image::ImageFormat::Png)
        .map_err(|e| e.to_string())?;
    Ok(buf)
}

/// Validate a spec, returning a normalized error message on bad input.
pub fn validate(spec: &BridgeSpec) -> Result<(), String> {
    if !spec.tech_name.starts_with("FS25_") {
        return Err("Bridge name must start with FS25_".into());
    }
    if spec.tech_name.chars().any(|c| !(c.is_ascii_alphanumeric() || c == '_')) {
        return Err("Bridge name may only contain letters, numbers and underscores".into());
    }
    if spec.fill_types.iter().all(|s| norm_name(s).is_empty()) {
        return Err("Pick at least one fill type to bridge".into());
    }
    if spec.categories.iter().all(|s| norm_name(s).is_empty()) {
        return Err("Pick at least one target category".into());
    }
    Ok(())
}

/// Write the companion mod zip (modDesc.xml + fillTypes.xml + icon.png) to `dest`.
pub fn generate(spec: &BridgeSpec, dest: &Path) -> Result<(), String> {
    validate(spec)?;
    let moddesc = build_moddesc(&spec.title, &spec.fill_types, &spec.categories);
    let fill_types = build_fill_types_xml(&spec.fill_types, &spec.categories);
    let icon = make_icon()?;

    let file = std::fs::File::create(dest).map_err(|e| e.to_string())?;
    let mut zip = zip::ZipWriter::new(file);
    let opts: zip::write::FileOptions<()> =
        zip::write::FileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    let mut put = |name: &str, bytes: &[u8]| -> Result<(), String> {
        zip.start_file(name, opts).map_err(|e| e.to_string())?;
        zip.write_all(bytes).map_err(|e| e.to_string())
    };
    put("modDesc.xml", moddesc.as_bytes())?;
    put("fillTypes.xml", fill_types.as_bytes())?;
    put("icon.png", &icon)?;
    zip.finish().map_err(|e| e.to_string())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fill_types_xml_lists_names_per_category() {
        let xml = build_fill_types_xml(
            &["sugarbeet".into(), "Beet Pulp".into()],
            &["BULK".into(), "shovel".into()],
        );
        // Names normalized (upper, junk stripped) and shared across each category.
        assert!(xml.contains("<fillTypeCategory name=\"BULK\">SUGARBEET BEETPULP</fillTypeCategory>"));
        assert!(xml.contains("<fillTypeCategory name=\"SHOVEL\">SUGARBEET BEETPULP</fillTypeCategory>"));
        assert!(xml.contains("<fillTypeCategories>"));
    }

    #[test]
    fn moddesc_is_wellformed_and_escapes_title() {
        let md = build_moddesc("Bob's <Bridge> & Co", &["X".into()], &["BULK".into()]);
        assert!(md.contains("descVersion=\"105\""));
        assert!(md.contains("<iconFilename>icon.png</iconFilename>"));
        assert!(md.contains("<fillTypes filename=\"fillTypes.xml\"/>"));
        assert!(md.contains("Bob&#39;s") || md.contains("Bob's")); // apostrophe left as-is is fine in element text
        assert!(md.contains("&lt;Bridge&gt;") && md.contains("&amp;"));
    }

    #[test]
    fn validate_rejects_bad_input() {
        let ok = BridgeSpec {
            tech_name: "FS25_Bridge".into(),
            title: "t".into(),
            fill_types: vec!["SUGARBEET".into()],
            categories: vec!["BULK".into()],
        };
        assert!(validate(&ok).is_ok());
        assert!(validate(&BridgeSpec { tech_name: "Bridge".into(), ..ok.clone() }).is_err()); // no FS25_
        assert!(validate(&BridgeSpec { fill_types: vec![],   ..ok.clone() }).is_err()); // no types
        assert!(validate(&BridgeSpec { categories: vec![],   ..ok.clone() }).is_err()); // no cats
        assert!(validate(&BridgeSpec { tech_name: "FS25_a b".into(), ..ok.clone() }).is_err()); // space
    }

    #[test]
    fn generate_writes_a_readable_zip() {
        let dir = std::env::temp_dir().join(format!("silo_bridge_test_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let dest = dir.join("FS25_TestBridge.zip");
        let spec = BridgeSpec {
            tech_name: "FS25_TestBridge".into(),
            title: "Test".into(),
            fill_types: vec!["SUGARBEET".into()],
            categories: vec!["BULK".into(), "SHOVEL".into()],
        };
        generate(&spec, &dest).unwrap();
        let f = std::fs::File::open(&dest).unwrap();
        let mut ar = zip::ZipArchive::new(f).unwrap();
        let names: Vec<String> = (0..ar.len()).map(|i| ar.by_index(i).unwrap().name().to_string()).collect();
        assert!(names.contains(&"modDesc.xml".to_string()));
        assert!(names.contains(&"fillTypes.xml".to_string()));
        assert!(names.contains(&"icon.png".to_string()));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
